
[[_Usage]]
= Usage

The following sections describe how you may use this plugin in an project.

== Configuration

This plugin relies on the {link_griffon_datasource_plugin}. Please follow the instructions to configure this plugin first.

The plugin's <<_modules, module>> registers a `{api_jdbi_handler}` helper class that defines the base contract
for accessing a datasource and issue SQL queries to it. This class has the following methods

[source,java,options="nowrap"]
.griffon.plugins.jdbi.JdbiHandler.java
----
include::{path_griffon_jdbi_core}/src/main/java//griffon/plugins/jdbi/JdbiHandler.java[tags=methods,indent=0]
----

These method are aware of multiple datasources. If no datasourceName is specified when calling them then the default
datasource will be selected. You can inject an instance of this class anywhere it's needed using `@Inject`. There is one
callback you may use with this method: `{api_jdbi_callback}`.

This callback is defined using a functional interface approach, which means you can apply lambda expressions if running
with JDK8+ or closures if running Groovy.

[source,java,options="nowrap"]
.griffon.plugins.jdbi.JdbiCallback.java
----
include::{path_griffon_jdbi_core}/src/main/java/griffon/plugins/jdbi/JdbiCallback.java[lines=25..-1]
----

=== Bootstrap

You may execute arbitrary database calls during connection and disconnection from a datasource. Simply
create a class that implements the `{api_jdbi_bootstrap}` interface and register it within a module, for example

[source,java,options="nowrap"]
.src/main/groovy/com/acme/SampleJdbiBootstrap.groovy
----
package com.acme

import griffon.plugins.jdbi.JdbiBootstrap
import org.skife.jdbi.v2.DBI

import javax.annotation.Nonnull
import javax.inject.Named

@Named("sample")
class SampleJdbiBootstrap implements JdbiBootstrap {
    @Override
    void init(@Nonnull String datasourceName, @Nonnull DBI dbi) {
        // operations after first connection to datasource
    }

    @Override
    void destroy(@Nonnull String datasourceName, @Nonnull DBI dbi) {
        // operations before disconnecting from the datasource
    }
}
----

[source,java,options="nowrap"]
.src/main/java/com/acme/ApplicationModule.java
----
package com.acme;

import griffon.plugins.jdbi.JdbiBootstrap;
import griffon.core.injection.Module;
import org.codehaus.griffon.runtime.core.injection.AbstractModule;
import org.kordamp.jipsy.ServiceProviderFor;

@ServiceProviderFor(Module.class)
public class ApplicationModule extends AbstractModule {
    @Override
    protected void doConfigure() {
        bind(JdbiBootstrap.class)
            .to(SampleJdbiBootstrap.class)
            .asSingleton();
    }
}
----

== Example

The following is a trivial usage of the `{api_jdbi_handler}` inside a service

[source,java,options="nowrap"]
.com.acme.SampleService.java
----
package com.acme;

import griffon.core.artifact.GriffonService;
import griffon.metadata.ArtifactProviderFor;
import org.codehaus.griffon.runtime.core.artifact.AbstractGriffonService;

import griffon.plugins.jdbi.JdbiHandler;
import griffon.plugins.jdbi.JdbiCallback;
import org.skife.jdbi.v2.DBI;

import javax.inject.Inject;

@ArtifactProviderFor(GriffonService.class)
public class SampleService {
    @Inject
    private JdbiHandler jdbiHandler

    public String getPersonName(final int id) {
         return jdbiHandler.withJdbi(new JdbiCallback<String>() {
             public String handle(@Nonnull String datasourceName, @Nonnull DBI dbi) {
                 PersonDAO dao = dbi.open(PersonDAO.class);
                 Person person = dao.findById(id);
                 return person != null ? person.getName() : null;
             }
         });
    }
}
----

== Events

The following events will be triggered by `{api_jdbi_handler}`

JdbiConnectStart(String datasourceName, Map<String, Object> config):: Triggered before connecting to the datasource.
JdbiConnectEnd(String datasourceName, Map<String, Object> config, DBI dbi):: Triggered after connecting to the datasource.
JdbiDisconnectStart(String datasourceName, Map<String, Object> config, DBI dbi):: Triggered before disconnecting from the datasource.
JdbiDisconnectEnd(String datasourceName, Map<String, Object> config):: Triggered after disconnecting from the datasource.

NOTE: DataSource events may be triggered during connection and disconnection from a datasource.

== AST Transformation

You can apply the `{api_jdbi_aware}` AST transformation on any class. This injects the behavior of `{api_jdbi_handler}`
into said class.

== DSL Descriptors

This plugin provides DSL descriptors for Intellij IDEA and Eclipse (provided you have the Groovy Eclipse plugin installed).
These descriptors are found inside the `griffon-jdbi-groovy-compile-{project-version}.jar`, with locations

 * dsdl/griffon_jdbi.dsld
 * gdsl/griffon_jdbi.gdsl
